"""Domain models — Core data structures for ResearchOS.

These models represent the fundamental concepts of the system.
All other layers reference these models. They have zero external dependencies.
"""

from datetime import datetime

from pydantic import BaseModel, Field


class Paper(BaseModel):
    """A research paper from any source (arXiv, PubMed, etc.)."""

    source_id: str = Field(description="ID from the source (e.g., arXiv ID)")
    source: str = Field(description="Source name: arxiv, pubmed, etc.")
    title: str
    authors: list[str] = Field(default_factory=list)
    abstract: str = ""
    published_date: datetime | None = None
    url: str = ""
    pdf_url: str = ""
    categories: list[str] = Field(default_factory=list)


class Chunk(BaseModel):
    """A chunk of text extracted from a paper, ready for embedding."""

    chunk_id: str
    paper_id: str
    text: str
    metadata: dict = Field(default_factory=dict)
    chunk_index: int = 0


class Document(BaseModel):
    """A document retrieved from a vector store."""

    doc_id: str
    text: str
    metadata: dict = Field(default_factory=dict)
    score: float = 0.0


class Message(BaseModel):
    """A single message in a conversation."""

    role: str = Field(description="system, user, or assistant")
    content: str


class SearchResult(BaseModel):
    """A single result from the retrieval pipeline."""

    chunk: Chunk
    score: float
    source: str = Field(description="Which retriever found this: vector, bm25, hybrid")


class Query(BaseModel):
    """A user query with optional configuration."""

    text: str
    top_k: int = 5
    sources: list[str] = Field(
        default_factory=lambda: ["arxiv", "pubmed"],
        description="Which sources to search",
    )


class GeneratedAnswer(BaseModel):
    """An answer generated by the LLM with source attribution."""

    answer: str
    sources: list[SearchResult] = Field(default_factory=list)
    model_used: str = ""
    tokens_used: int = 0
